# -*- coding: utf-8 -*-
"""Jailbreaking_Starter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCtX-QBSwv5wlrkZ0fSMMHGWJXqQjZaE
"""

!pip install fschat
!pip install openai==0.28

import os
os.environ['OPENAI_API_KEY'] = "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"
from KOV import startKOV

startKOV("advbench_subset.csv", "lmsys/vicuna-7b-v1.5")

